### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by squidfunk** [ojacques/mkdocs-git-committers-plugin-2#17]
The latest git-comitters-plugin fails due to the use of a package that is not listed as a dependency:
https://github.com/squidfunk/mkdocs-material/runs/8130815276?check_suite_focus=true#step:7:56

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 209, in gh_deploy_command
    cfg = config.load_config(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 224, in load_config
    errors, warnings = cfg.validate()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 108, in validate
    run_failed, run_warnings = self._validate()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/base.py", line 63, in _validate
    self[key] = config_option.validate(value)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 132, in validate
    return self.run_validation(value)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 690, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 703, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line [18](https://github.com/squidfunk/mkdocs-material/runs/8130815276?check_suite_focus=true#step:7:19), in <module>
    from bs4 import BeautifulSoup as bs
ModuleNotFoundError: No module named 'bs4'
```

**Comment by ojacques** [comment]
Thanks for the report! 
Fixed now with 1.0.1.
```
Installing collected packages: zipp, watchdog, urllib3, soupsieve, smmap, six, PyYAML, pyparsing, mergedeep, MarkupSafe, Markdown, idna, click, charset-normalizer, certifi, requests, pyyaml-env-tag, python-dateutil, packaging, Jinja2, importlib-metadata, gitdb, beautifulsoup4, gitpython, ghp-import, mkdocs, mkdocs-git-committers-plugin-2
```
