### ISSUE TITLE
IndexError when there are no commits/contributors in the source repository

### ISSUE THREAD

**Issue by pawamoy** [ojacques/mkdocs-git-committers-plugin-2#29]
I'm building the docs for a public repository from a private fork (for reasons :joy:).
If the repository specified in the configuration has no commits, and therefore no contributors, this plugin crashes with an index error:

```console
% DEPLOY=true make docs 
INFO     -  Building documentation...
INFO     -  git-committers plugin ENABLED
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - coverage.md
INFO     -  git-committers: fetching contributors for docs/index.md
ERROR    -  Error building page 'index.md': list index out of range
Traceback (most recent call last):
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/failprint/runners.py", line 223, in run_function_get_code
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/failprint/lazy.py", line 37, in __call__
    return self.call(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/duty/callables/mkdocs.py", line 256, in serve
    run("serve", *cli_args, quiet=quiet, verbose=verbose)
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/duty/callables/mkdocs.py", line 26, in run
    mkdocs(cli_args)
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs/commands/build.py", line 226, in _build_page
    context = config.plugins.run_event(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs_git_committers_plugin_2/plugin.py", line 122, in on_page_context
    authors, last_commit_date = self.list_contributors(git_path)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/pypi-insiders/__pypackages__/3.11/lib/mkdocs_git_committers_plugin_2/plugin.py", line 108, in list_contributors
    avatar = img_tags[0]['src']
             ~~~~~~~~^^^
IndexError: list index out of range
```

The workaround I used was to create a 3-lines README in the public repository. The plugin then worked as expected (404 for each page, as expected, but not crashing).

My config for this plugin in mkdocs.yml:

```yaml
plugins:
- git-committers:
    enabled: !ENV [DEPLOY, false]
    repository: pawamoy/pypi-insiders
```

**Comment by ojacques** [comment]
This should not happen anymore, as we don't query authors like this anymore since [2.0.0](https://github.com/ojacques/mkdocs-git-committers-plugin-2/releases/tag/2.0.0).
Thanks for the report! Closing.

**Comment by pawamoy** [comment]
Thank you so much @ojacques!
